# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40493b2910a51f8f892b0cf545108baa"
name = "branded-marchent-ship"
handle = "branded-marchent-ship"
application_url = "https://kirk-soc-dialog-pearl.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kirk-soc-dialog-pearl.trycloudflare.com/auth/callback",
  "https://kirk-soc-dialog-pearl.trycloudflare.com/auth/shopify/callback",
  "https://kirk-soc-dialog-pearl.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-feac0727.myshopify.com"
automatically_update_urls_on_dev = true
